/* user */
CREATE TABLE [user](
	[id] UNIQUEIDENTIFIER NOT NULL PRIMARY KEY,
	[name] TEXT NOT NULL
)

/* event */
CREATE TABLE [event](
	[id] UNIQUEIDENTIFIER NOT NULL PRIMARY KEY,
	[user_id] UNIQUEIDENTIFIER NOT NULL,
	[description] TEXT NOT NULL,
	CONSTRAINT [FK_event_user] FOREIGN KEY([user_id]) REFERENCES [user]([id])
)
